name: virtual_cues
description: A mobile version of virtual cues.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  # firebase_auth: ^4.19.0
  # firebase_core: ^2.29.0
  flutter_hot_toast: ^0.0.3
  fl_query: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.1.0
  google_fonts: 6.1.0
  google_sign_in: ^6.2.1
  intl: ^0.18.0
  ionicons: ^0.2.2
  json_annotation: ^4.8.1
  skeletonizer: ^1.0.1
  persistent_bottom_nav_bar: ^5.0.2
  url_launcher: ^6.2.6
  animate_do: ^3.3.4
  gap: ^3.0.1
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  retrofit_generator: ^8.0.6
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/icon/shield.png"
  image_path_ios: "assets/icon/shield.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/

